name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
# Options
          user: M0nkeyPr0grammer
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_gists: no
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_skipped: dotfiles
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_people: no
          plugin_projects: no
          plugin_stars: no
